#!/usr/bin/env bash
set -e

if [[ $(tput lines) > 35 ]]; then
  preview_height=30
elif [[ $(tput lines) > 25 ]]; then
  preview_height=20
else
  preview_height=0
fi

if [[ "$1" == "mine" ]]; then
  GH_FORCE_TTY='100%' gh issue list --state all --assignee @me --limit 200 |
    tail -n +4 |
    fzf --ansi \
      --preview-window down:$preview_height \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh issue view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh issue view --web {}
else
  GH_FORCE_TTY='100%' gh issue list --state all --limit 100 |
    tail -n +4 |
    fzf --ansi \
      --preview-window down:$preview_height \
      --bind ctrl-d:preview-down \
      --bind ctrl-u:preview-up \
      --preview 'GH_FORCE_TTY=$FZF_PREVIEW_COLUMNS gh issue view {1} | bat --color always -l md' |
    awk '{print $1}' |
    tr -d '#' |
    xargs -I {} gh issue view --web {}
fi
